"""Initial migration

Revision ID: b2c329b2b2d2
Revises: 
Create Date: 2025-07-13 20:11:11.687717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c329b2b2d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('criadoem', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('adversario', sa.String(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('golspro', sa.Integer(), nullable=True),
    sa.Column('golscontra', sa.Integer(), nullable=True),
    sa.Column('torneio', sa.String(), nullable=True),
    sa.Column('datajogo', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('tecnico', sa.String(), nullable=True),
    sa.Column('criadoem', sa.DateTime(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
